[package]
name = "ln-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ln-lib = { path = "../ln-lib" }
skim = "0.9.4"
tokio = { version = "1.17.0", features = ["full"] }
